### ISSUE TITLE
make splash page overlay div 

### ISSUE THREAD

**Issue by radames** [youthradio/NeverAgain-Front#2]
move splash page to main page, making it overlay the page

**Comment by AshaLaura** [comment]
Seth worked on this but it's not merged.

**Comment by AshaLaura** [comment]
Seth added jQuery to toggle between splash page and main. It's fade-in and fade-out, but it's not very smooth yet. I'll ask him for his code today.

**Comment by radames** [comment]
cool, I can help with the merging today
